// Code generated by mockery v2.38.0. DO NOT EDIT.

package lists

import mock "github.com/stretchr/testify/mock"

// MockCycleLinkFunc is an autogenerated mock type for the CycleLinkFunc type
type MockCycleLinkFunc[T interface{}] struct {
	mock.Mock
}

type MockCycleLinkFunc_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *MockCycleLinkFunc[T]) EXPECT() *MockCycleLinkFunc_Expecter[T] {
	return &MockCycleLinkFunc_Expecter[T]{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockCycleLinkFunc[T]) Execute(_a0 T) {
	_m.Called(_a0)
}

// MockCycleLinkFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCycleLinkFunc_Execute_Call[T interface{}] struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 T
func (_e *MockCycleLinkFunc_Expecter[T]) Execute(_a0 interface{}) *MockCycleLinkFunc_Execute_Call[T] {
	return &MockCycleLinkFunc_Execute_Call[T]{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockCycleLinkFunc_Execute_Call[T]) Run(run func(_a0 T)) *MockCycleLinkFunc_Execute_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(T))
	})
	return _c
}

func (_c *MockCycleLinkFunc_Execute_Call[T]) Return() *MockCycleLinkFunc_Execute_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockCycleLinkFunc_Execute_Call[T]) RunAndReturn(run func(T)) *MockCycleLinkFunc_Execute_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockCycleLinkFunc creates a new instance of MockCycleLinkFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCycleLinkFunc[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCycleLinkFunc[T] {
	mock := &MockCycleLinkFunc[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
