// Code generated by mockery v2.38.0. DO NOT EDIT.

package lists

import mock "github.com/stretchr/testify/mock"

// MockOnEach is an autogenerated mock type for the OnEach type
type MockOnEach[T interface{}] struct {
	mock.Mock
}

type MockOnEach_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *MockOnEach[T]) EXPECT() *MockOnEach_Expecter[T] {
	return &MockOnEach_Expecter[T]{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: value
func (_m *MockOnEach[T]) Execute(value *T) error {
	ret := _m.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*T) error); ok {
		r0 = rf(value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOnEach_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockOnEach_Execute_Call[T interface{}] struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - value *T
func (_e *MockOnEach_Expecter[T]) Execute(value interface{}) *MockOnEach_Execute_Call[T] {
	return &MockOnEach_Execute_Call[T]{Call: _e.mock.On("Execute", value)}
}

func (_c *MockOnEach_Execute_Call[T]) Run(run func(value *T)) *MockOnEach_Execute_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*T))
	})
	return _c
}

func (_c *MockOnEach_Execute_Call[T]) Return(_a0 error) *MockOnEach_Execute_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOnEach_Execute_Call[T]) RunAndReturn(run func(*T) error) *MockOnEach_Execute_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockOnEach creates a new instance of MockOnEach. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOnEach[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOnEach[T] {
	mock := &MockOnEach[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
